services:

  postgres:
    image: postgres:latest
    container_name: postgresWiSe012
    environment:
      POSTGRES_USER: postgrestgm
      POSTGRES_PASSWORD: gordlbypassword
      POSTGRES_DB: webshop
    ports:
      - "5432:5432"
    volumes:
     - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminWiSe012
    environment:
      PGADMIN_DEFAULT_EMAIL: postgrestgm@gordlby.at
      PGADMIN_DEFAULT_PASSWORD: M5Wv@4Vr*^1r3@85sS3N
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - /Users/marcprochazka/Library/CloudStorage/OneDrive-tgm-DieSchulederTechnik/01_4BHIT/INSY/WiSe012/data/pgadmin:/var/lib/pgadmin

volumes:
  postgres-data: